# for manual exception handling
#spring:
#  rabbitmq:
#    listener:
#      simple:
#        acknowledge-mode: manual

spring:
  rabbitmq:
    host:
    username:
    virtual-host:
    password:
    listener:
      simple:
        # only for automatic ack mode
        retry:
          enabled: true
          initial-interval: 3s
          max-interval: 10s
          max-attempts: 5
          multiplier: 2

# for setting prefetch count (for fast producer and slow consumers)
#spring:
#  rabbitmq:
#    listener:
#      simple:
#        prefetch: 1

# for getting message publishing status
#spring:
#  rabbitmq:
#    publisher-confirm-type: correlated
#    publisher-returns: true
#    template:
#      mandatory: true

